### DISCUSSION TITLE
Change size of ColorPicker

### DISCUSSION THREAD

**Discussion by dd8888** [mikbry/material-ui-color#115] [Q&A]
Hello! I was wondering if there was any way of changing the size of the button that opens the ColorPicker, because I've been trying to find one but nothing seemed to work. And it's weird because inspecting the component there is a "size" prop that does what I need, but I don't really know how can I access that. Thank you in advance.

**Comment by mikbry** [comment]
You could extend `muicc-colorpicker-button` class using css:
```css
.muicc-color-picker-button {
  width: 48px;
  height: 48px;
}
```
